# -*- coding: utf-8 -*-
{
    'name': 'Manufacturing Services',
    'version': '14.0.1.0',
    'category': 'Proof of Concept',
    'summary': 'Services Tab on Manufacturing Orders. Added to product cost.',
    'description': u"""
This module has been generated by Odoo Studio.
It contains the apps created with Studio and the customizations of existing apps.
""",
    'author': 'Odoo Technical Marketing',
    'depends': [
        'mrp_account_enterprise',
        'product',
        'web_studio',
    ],
    'data': [
        'data/ir_model.xml',
        'data/ir_model_fields.xml',
        'data/ir_ui_view.xml',
		'data/ir_model_access.xml',
    ],
    'application': False,
    'license': 'OPL-1',
    'support': 'Unsupported',
    'images': [
        'images/main_screenshot.png'
    ],
}
