# -*- coding: utf-8 -*-
{
    'name': 'Check Remit To',
    'version': '14.0.1.1',
    'category': 'Proof of Concept',
    'summary': 'Studio App: Support checks with remit to contact information',
    'description': u"""
This module has been generated by Odoo Studio.
It contains the apps created with Studio and the customizations of existing apps.
""",
    'author': 'Odoo Technical Marketing',
    'depends': [
        'base',
        'account_accountant',
        'l10n_us_check_printing',
        'web_studio',
    ],
    'data': [
        'data/ir_model_fields.xml',
        'data/ir_ui_view.xml',
    ],
    'application': False,
    'license': 'OPL-1',
    'support': 'Unsupported',
    'images': [
        'images/main_screenshot.png'
    ],
}
